In [1]:
%matplotlib inline
%matplotlib notebook

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from dummy import *

In [59]:
subs = generate_submissions()
badSubs = subs[subs.veredict != 'AC']
goodSubs = subs[subs.veredict == 'AC']

In [60]:
bm = bianary_mat(subs)
bm

U00000  U00001  U00002  U00003
P00000       0       1       0       0
P00001       1       1       0       0
P00002       0       0       1       0
P00003       0       1       0       1
P00004       0       0       1       0
P00005       0       0       0       1
P00006       0       0       0       1
P00007       0       0       0       1

In [61]:
bmm = bm.as_matrix()

In [62]:
U, s, V = np.linalg.svd(bmm, full_matrices=False)

In [63]:
print U

[[ 0.26131615  0.42837644  0.         -0.56536366]
 [ 0.33194924  0.67165096  0.          0.66234031]
 [ 0.          0.          0.70710678  0.        ]
 [ 0.63482335  0.08266714  0.         -0.4019876 ]
 [ 0.          0.          0.70710678  0.        ]
 [ 0.3735072  -0.3457093   0.          0.16337606]
 [ 0.3735072  -0.3457093   0.          0.16337606]
 [ 0.3735072  -0.3457093   0.          0.16337606]]


In [64]:
Uv = pd.DataFrame(U)[0]
print Uv

0    0.261316
1    0.331949
2    0.000000
3    0.634823
4    0.000000
5    0.373507
6    0.373507
7    0.373507
Name: 0, dtype: float64


In [65]:
print s
s[0]

[ 2.16786258  1.66158861  1.41421356  0.73450332]


2.1678625759663173

In [66]:
print V
V[0]

[[ 0.15312282  0.5664975   0.          0.80971228]
 [ 0.40422217  0.71178541  0.         -0.57442663]
 [-0.         -0.          1.          0.        ]
 [ 0.90175265 -0.41526149  0.          0.12000026]]


array([ 0.15312282,  0.5664975 ,  0.        ,  0.80971228])

In [67]:
magnitude(Uv)

1.0

In [68]:
magnitude(V[0])

1.0

Let's evaluate the results for player 0

In [79]:
ability = V[0][3]
scale = s[0]
difficulties = Uv

In [80]:
print ability
print scale
print difficulties

0.809712281593
2.16786257597
0    0.261316
1    0.331949
2    0.000000
3    0.634823
4    0.000000
5    0.373507
6    0.373507
7    0.373507
Name: 0, dtype: float64


In [81]:
difficulties.apply(lambda x: ability*scale*x)

0    0.458700
1    0.582685
2    0.000000
3    1.114334
4    0.000000
5    0.655634
6    0.655634
7    0.655634
Name: 0, dtype: float64

# Example of vector multiplication

In [99]:
x1 = np.arange(9.0).reshape((9, 1))
x2 = np.arange(3.0)
print "x1 => ", x1
print "x2 => ", x2

x1 =>  [[ 0.]
 [ 1.]
 [ 2.]
 [ 3.]
 [ 4.]
 [ 5.]
 [ 6.]
 [ 7.]
 [ 8.]]
x2 =>  [ 0.  1.  2.]


In [100]:
np.multiply(x1, x2)

array([[  0.,   0.,   0.],
       [  0.,   1.,   2.],
       [  0.,   2.,   4.],
       [  0.,   3.,   6.],
       [  0.,   4.,   8.],
       [  0.,   5.,  10.],
       [  0.,   6.,  12.],
       [  0.,   7.,  14.],
       [  0.,   8.,  16.]])

In [107]:
Abilties = V[0]
print Abilties

[ 0.15312282  0.5664975   0.          0.80971228]


In [108]:
Difficulties = U[:,[0]]
print Difficulties

[[ 0.26131615]
 [ 0.33194924]
 [ 0.        ]
 [ 0.63482335]
 [ 0.        ]
 [ 0.3735072 ]
 [ 0.3735072 ]
 [ 0.3735072 ]]


# Reconstruction de la matrice :

In [120]:
data = np.multiply(Abilties, Difficulties) * scale
recBm = pd.DataFrame(data, columns=bm.columns, index=bm.index)
recBm

U00000    U00001  U00002    U00003
P00000  0.086744  0.320919     0.0  0.458700
P00001  0.110190  0.407663     0.0  0.582685
P00002  0.000000  0.000000     0.0  0.000000
P00003  0.210729  0.779619     0.0  1.114334
P00004  0.000000  0.000000     0.0  0.000000
P00005  0.123985  0.458700     0.0  0.655634
P00006  0.123985  0.458700     0.0  0.655634
P00007  0.123985  0.458700     0.0  0.655634

In [121]:
bm

U00000  U00001  U00002  U00003
P00000       0       1       0       0
P00001       1       1       0       0
P00002       0       0       1       0
P00003       0       1       0       1
P00004       0       0       1       0
P00005       0       0       0       1
P00006       0       0       0       1
P00007       0       0       0       1

In [158]:
def rond(x):
    treshold=0.5
    return x>treshold
    # return int(x>treshold)

In [168]:
recBm.apply(rond).astype(int)

U00000  U00001  U00002  U00003
P00000       0       0       0       0
P00001       0       0       0       1
P00002       0       0       0       0
P00003       0       1       0       1
P00004       0       0       0       0
P00005       0       0       0       1
P00006       0       0       0       1
P00007       0       0       0       1

In [169]:
bm

U00000  U00001  U00002  U00003
P00000       0       1       0       0
P00001       1       1       0       0
P00002       0       0       1       0
P00003       0       1       0       1
P00004       0       0       1       0
P00005       0       0       0       1
P00006       0       0       0       1
P00007       0       0       0       1